///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SomeRootEntityItemsSearchInfo {
/*
{
  "textSnippet": "This work is unofficial and is not authorized by the Tolkien Estate or HarperCollins Publishers."
} 
*/

  String? textSnippet;

  SomeRootEntityItemsSearchInfo({
    this.textSnippet,
  });
  SomeRootEntityItemsSearchInfo.fromJson(Map<String, dynamic> json) {
    textSnippet = json['textSnippet']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['textSnippet'] = textSnippet;
    return data;
  }
}

class SomeRootEntityItemsAccessInfoPdf {
/*
{
  "isAvailable": false
} 
*/

  bool? isAvailable;

  SomeRootEntityItemsAccessInfoPdf({
    this.isAvailable,
  });
  SomeRootEntityItemsAccessInfoPdf.fromJson(Map<String, dynamic> json) {
    isAvailable = json['isAvailable'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isAvailable'] = isAvailable;
    return data;
  }
}

class SomeRootEntityItemsAccessInfoEpub {
/*
{
  "isAvailable": true,
  "acsTokenLink": "http://books.google.com.tr/books/download/The_Illustrated_World_of_Tolkien-sample-epub.acsm?id=RMCtDwAAQBAJ&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api"
} 
*/

  bool? isAvailable;
  String? acsTokenLink;

  SomeRootEntityItemsAccessInfoEpub({
    this.isAvailable,
    this.acsTokenLink,
  });
  SomeRootEntityItemsAccessInfoEpub.fromJson(Map<String, dynamic> json) {
    isAvailable = json['isAvailable'];
    acsTokenLink = json['acsTokenLink']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isAvailable'] = isAvailable;
    data['acsTokenLink'] = acsTokenLink;
    return data;
  }
}

class SomeRootEntityItemsAccessInfo {
/*
{
  "country": "TR",
  "viewability": "PARTIAL",
  "embeddable": true,
  "publicDomain": false,
  "textToSpeechPermission": "ALLOWED",
  "epub": {
    "isAvailable": true,
    "acsTokenLink": "http://books.google.com.tr/books/download/The_Illustrated_World_of_Tolkien-sample-epub.acsm?id=RMCtDwAAQBAJ&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api"
  },
  "pdf": {
    "isAvailable": false
  },
  "webReaderLink": "http://play.google.com/books/reader?id=RMCtDwAAQBAJ&hl=&source=gbs_api",
  "accessViewStatus": "SAMPLE",
  "quoteSharingAllowed": false
} 
*/

  String? country;
  String? viewability;
  bool? embeddable;
  bool? publicDomain;
  String? textToSpeechPermission;
  SomeRootEntityItemsAccessInfoEpub? epub;
  SomeRootEntityItemsAccessInfoPdf? pdf;
  String? webReaderLink;
  String? accessViewStatus;
  bool? quoteSharingAllowed;

  SomeRootEntityItemsAccessInfo({
    this.country,
    this.viewability,
    this.embeddable,
    this.publicDomain,
    this.textToSpeechPermission,
    this.epub,
    this.pdf,
    this.webReaderLink,
    this.accessViewStatus,
    this.quoteSharingAllowed,
  });
  SomeRootEntityItemsAccessInfo.fromJson(Map<String, dynamic> json) {
    country = json['country']?.toString();
    viewability = json['viewability']?.toString();
    embeddable = json['embeddable'];
    publicDomain = json['publicDomain'];
    textToSpeechPermission = json['textToSpeechPermission']?.toString();
    epub = (json['epub'] != null)
        ? SomeRootEntityItemsAccessInfoEpub.fromJson(json['epub'])
        : null;
    pdf = (json['pdf'] != null)
        ? SomeRootEntityItemsAccessInfoPdf.fromJson(json['pdf'])
        : null;
    webReaderLink = json['webReaderLink']?.toString();
    accessViewStatus = json['accessViewStatus']?.toString();
    quoteSharingAllowed = json['quoteSharingAllowed'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['viewability'] = viewability;
    data['embeddable'] = embeddable;
    data['publicDomain'] = publicDomain;
    data['textToSpeechPermission'] = textToSpeechPermission;
    if (epub != null) {
      data['epub'] = epub!.toJson();
    }
    if (pdf != null) {
      data['pdf'] = pdf!.toJson();
    }
    data['webReaderLink'] = webReaderLink;
    data['accessViewStatus'] = accessViewStatus;
    data['quoteSharingAllowed'] = quoteSharingAllowed;
    return data;
  }
}

class SomeRootEntityItemsSaleInfoOffersRetailPrice {
/*
{
  "amountInMicros": 1360550000,
  "currencyCode": "TRY"
} 
*/

  int? amountInMicros;
  String? currencyCode;

  SomeRootEntityItemsSaleInfoOffersRetailPrice({
    this.amountInMicros,
    this.currencyCode,
  });
  SomeRootEntityItemsSaleInfoOffersRetailPrice.fromJson(
      Map<String, dynamic> json) {
    amountInMicros = json['amountInMicros']?.toInt();
    currencyCode = json['currencyCode']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amountInMicros'] = amountInMicros;
    data['currencyCode'] = currencyCode;
    return data;
  }
}

class SomeRootEntityItemsSaleInfoOffersListPrice {
/*
{
  "amountInMicros": 1360550000,
  "currencyCode": "TRY"
} 
*/

  int? amountInMicros;
  String? currencyCode;

  SomeRootEntityItemsSaleInfoOffersListPrice({
    this.amountInMicros,
    this.currencyCode,
  });
  SomeRootEntityItemsSaleInfoOffersListPrice.fromJson(
      Map<String, dynamic> json) {
    amountInMicros = json['amountInMicros']?.toInt();
    currencyCode = json['currencyCode']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amountInMicros'] = amountInMicros;
    data['currencyCode'] = currencyCode;
    return data;
  }
}

class SomeRootEntityItemsSaleInfoOffers {
/*
{
  "finskyOfferType": 1,
  "listPrice": {
    "amountInMicros": 1360550000,
    "currencyCode": "TRY"
  },
  "retailPrice": {
    "amountInMicros": 1360550000,
    "currencyCode": "TRY"
  }
} 
*/

  int? finskyOfferType;
  SomeRootEntityItemsSaleInfoOffersListPrice? listPrice;
  SomeRootEntityItemsSaleInfoOffersRetailPrice? retailPrice;

  SomeRootEntityItemsSaleInfoOffers({
    this.finskyOfferType,
    this.listPrice,
    this.retailPrice,
  });
  SomeRootEntityItemsSaleInfoOffers.fromJson(Map<String, dynamic> json) {
    finskyOfferType = json['finskyOfferType']?.toInt();
    listPrice = (json['listPrice'] != null)
        ? SomeRootEntityItemsSaleInfoOffersListPrice.fromJson(json['listPrice'])
        : null;
    retailPrice = (json['retailPrice'] != null)
        ? SomeRootEntityItemsSaleInfoOffersRetailPrice.fromJson(
            json['retailPrice'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['finskyOfferType'] = finskyOfferType;
    if (listPrice != null) {
      data['listPrice'] = listPrice!.toJson();
    }
    if (retailPrice != null) {
      data['retailPrice'] = retailPrice!.toJson();
    }
    return data;
  }
}

class SomeRootEntityItemsSaleInfoRetailPrice {
/*
{
  "amount": 1360.55,
  "currencyCode": "TRY"
} 
*/

  double? amount;
  String? currencyCode;

  SomeRootEntityItemsSaleInfoRetailPrice({
    this.amount,
    this.currencyCode,
  });
  SomeRootEntityItemsSaleInfoRetailPrice.fromJson(Map<String, dynamic> json) {
    amount = json['amount']?.toDouble();
    currencyCode = json['currencyCode']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amount'] = amount;
    data['currencyCode'] = currencyCode;
    return data;
  }
}

class SomeRootEntityItemsSaleInfoListPrice {
/*
{
  "amount": 1360.55,
  "currencyCode": "TRY"
} 
*/

  double? amount;
  String? currencyCode;

  SomeRootEntityItemsSaleInfoListPrice({
    this.amount,
    this.currencyCode,
  });
  SomeRootEntityItemsSaleInfoListPrice.fromJson(Map<String, dynamic> json) {
    amount = json['amount']?.toDouble();
    currencyCode = json['currencyCode']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amount'] = amount;
    data['currencyCode'] = currencyCode;
    return data;
  }
}

class SomeRootEntityItemsSaleInfo {
/*
{
  "country": "TR",
  "saleability": "FOR_SALE",
  "isEbook": true,
  "listPrice": {
    "amount": 1360.55,
    "currencyCode": "TRY"
  },
  "retailPrice": {
    "amount": 1360.55,
    "currencyCode": "TRY"
  },
  "buyLink": "https://play.google.com/store/books/details?id=RMCtDwAAQBAJ&rdid=book-RMCtDwAAQBAJ&rdot=1&source=gbs_api",
  "offers": [
    {
      "finskyOfferType": 1,
      "listPrice": {
        "amountInMicros": 1360550000,
        "currencyCode": "TRY"
      },
      "retailPrice": {
        "amountInMicros": 1360550000,
        "currencyCode": "TRY"
      }
    }
  ]
} 
*/

  String? country;
  String? saleability;
  bool? isEbook;
  SomeRootEntityItemsSaleInfoListPrice? listPrice;
  SomeRootEntityItemsSaleInfoRetailPrice? retailPrice;
  String? buyLink;
  List<SomeRootEntityItemsSaleInfoOffers?>? offers;

  SomeRootEntityItemsSaleInfo({
    this.country,
    this.saleability,
    this.isEbook,
    this.listPrice,
    this.retailPrice,
    this.buyLink,
    this.offers,
  });
  SomeRootEntityItemsSaleInfo.fromJson(Map<String, dynamic> json) {
    country = json['country']?.toString();
    saleability = json['saleability']?.toString();
    isEbook = json['isEbook'];
    listPrice = (json['listPrice'] != null)
        ? SomeRootEntityItemsSaleInfoListPrice.fromJson(json['listPrice'])
        : null;
    retailPrice = (json['retailPrice'] != null)
        ? SomeRootEntityItemsSaleInfoRetailPrice.fromJson(json['retailPrice'])
        : null;
    buyLink = json['buyLink']?.toString();
    if (json['offers'] != null) {
      final v = json['offers'];
      final arr0 = <SomeRootEntityItemsSaleInfoOffers>[];
      v.forEach((v) {
        arr0.add(SomeRootEntityItemsSaleInfoOffers.fromJson(v));
      });
      offers = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['saleability'] = saleability;
    data['isEbook'] = isEbook;
    if (listPrice != null) {
      data['listPrice'] = listPrice!.toJson();
    }
    if (retailPrice != null) {
      data['retailPrice'] = retailPrice!.toJson();
    }
    data['buyLink'] = buyLink;
    if (offers != null) {
      final v = offers;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['offers'] = arr0;
    }
    return data;
  }
}

class SomeRootEntityItemsVolumeInfoImageLinks {
/*
{
  "smallThumbnail": "http://books.google.com/books/content?id=RMCtDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
  "thumbnail": "http://books.google.com/books/content?id=RMCtDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
} 
*/

  String? smallThumbnail;
  String? thumbnail;

  SomeRootEntityItemsVolumeInfoImageLinks({
    this.smallThumbnail,
    this.thumbnail,
  });
  SomeRootEntityItemsVolumeInfoImageLinks.fromJson(Map<String, dynamic> json) {
    smallThumbnail = json['smallThumbnail']?.toString();
    thumbnail = json['thumbnail']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['smallThumbnail'] = smallThumbnail;
    data['thumbnail'] = thumbnail;
    return data;
  }
}

class SomeRootEntityItemsVolumeInfoPanelizationSummary {
/*
{
  "containsEpubBubbles": false,
  "containsImageBubbles": false
} 
*/

  bool? containsEpubBubbles;
  bool? containsImageBubbles;

  SomeRootEntityItemsVolumeInfoPanelizationSummary({
    this.containsEpubBubbles,
    this.containsImageBubbles,
  });
  SomeRootEntityItemsVolumeInfoPanelizationSummary.fromJson(
      Map<String, dynamic> json) {
    containsEpubBubbles = json['containsEpubBubbles'];
    containsImageBubbles = json['containsImageBubbles'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['containsEpubBubbles'] = containsEpubBubbles;
    data['containsImageBubbles'] = containsImageBubbles;
    return data;
  }
}

class SomeRootEntityItemsVolumeInfoReadingModes {
/*
{
  "text": true,
  "image": false
} 
*/

  bool? text;
  bool? image;

  SomeRootEntityItemsVolumeInfoReadingModes({
    this.text,
    this.image,
  });
  SomeRootEntityItemsVolumeInfoReadingModes.fromJson(
      Map<String, dynamic> json) {
    text = json['text'];
    image = json['image'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['text'] = text;
    data['image'] = image;
    return data;
  }
}

class SomeRootEntityItemsVolumeInfoIndustryIdentifiers {
/*
{
  "type": "ISBN_13",
  "identifier": "9780753734049"
} 
*/

  String? type;
  String? identifier;

  SomeRootEntityItemsVolumeInfoIndustryIdentifiers({
    this.type,
    this.identifier,
  });
  SomeRootEntityItemsVolumeInfoIndustryIdentifiers.fromJson(
      Map<String, dynamic> json) {
    type = json['type']?.toString();
    identifier = json['identifier']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    data['identifier'] = identifier;
    return data;
  }
}

class SomeRootEntityItemsVolumeInfo {
/*
{
  "title": "The Illustrated World of Tolkien",
  "subtitle": "An Exquisite Reference Guide to Tolkien's World and the Artists his Vision Inspired",
  "authors": [
    "David Day"
  ],
  "publisher": "Hachette UK",
  "publishedDate": "2019-10-19",
  "description": "Tolkien's works have inspired artists for generations and have given rise to myriad interpretations of the rich and magical worlds he created. The Illustrated World of Tolkien gathers together artworks and essays from expert illustrators, painters and etchers, and fascinating and scholarly writing from renowned Tolkien expert David Day, and is an exquisite reference guide for any fan of Tolkien's work, Tolkien's world and the imaginative brilliance his vision inspired. This work is unofficial and is not authorized by the Tolkien Estate or HarperCollins Publishers.",
  "industryIdentifiers": [
    {
      "type": "ISBN_13",
      "identifier": "9780753734049"
    }
  ],
  "readingModes": {
    "text": true,
    "image": false
  },
  "pageCount": 288,
  "printType": "BOOK",
  "categories": [
    "Art"
  ],
  "maturityRating": "NOT_MATURE",
  "allowAnonLogging": true,
  "contentVersion": "1.2.2.0.preview.2",
  "panelizationSummary": {
    "containsEpubBubbles": false,
    "containsImageBubbles": false
  },
  "imageLinks": {
    "smallThumbnail": "http://books.google.com/books/content?id=RMCtDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "thumbnail": "http://books.google.com/books/content?id=RMCtDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
  },
  "language": "en",
  "previewLink": "http://books.google.com.tr/books?id=RMCtDwAAQBAJ&printsec=frontcover&dq=Tolkien&hl=&cd=21&source=gbs_api",
  "infoLink": "https://play.google.com/store/books/details?id=RMCtDwAAQBAJ&source=gbs_api",
  "canonicalVolumeLink": "https://play.google.com/store/books/details?id=RMCtDwAAQBAJ"
} 
*/

  String? title;
  String? subtitle;
  List<String?>? authors;
  String? publisher;
  String? publishedDate;
  String? description;
  List<SomeRootEntityItemsVolumeInfoIndustryIdentifiers?>? industryIdentifiers;
  SomeRootEntityItemsVolumeInfoReadingModes? readingModes;
  int? pageCount;
  String? printType;
  List<String?>? categories;
  String? maturityRating;
  bool? allowAnonLogging;
  String? contentVersion;
  SomeRootEntityItemsVolumeInfoPanelizationSummary? panelizationSummary;
  SomeRootEntityItemsVolumeInfoImageLinks? imageLinks;
  String? language;
  String? previewLink;
  String? infoLink;
  String? canonicalVolumeLink;

  SomeRootEntityItemsVolumeInfo({
    this.title,
    this.subtitle,
    this.authors,
    this.publisher,
    this.publishedDate,
    this.description,
    this.industryIdentifiers,
    this.readingModes,
    this.pageCount,
    this.printType,
    this.categories,
    this.maturityRating,
    this.allowAnonLogging,
    this.contentVersion,
    this.panelizationSummary,
    this.imageLinks,
    this.language,
    this.previewLink,
    this.infoLink,
    this.canonicalVolumeLink,
  });
  SomeRootEntityItemsVolumeInfo.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    subtitle = json['subtitle']?.toString();
    if (json['authors'] != null) {
      final v = json['authors'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      authors = arr0;
    }
    publisher = json['publisher']?.toString();
    publishedDate = json['publishedDate']?.toString();
    description = json['description']?.toString();
    if (json['industryIdentifiers'] != null) {
      final v = json['industryIdentifiers'];
      final arr0 = <SomeRootEntityItemsVolumeInfoIndustryIdentifiers>[];
      v.forEach((v) {
        arr0.add(SomeRootEntityItemsVolumeInfoIndustryIdentifiers.fromJson(v));
      });
      industryIdentifiers = arr0;
    }
    readingModes = (json['readingModes'] != null)
        ? SomeRootEntityItemsVolumeInfoReadingModes.fromJson(
            json['readingModes'])
        : null;
    pageCount = json['pageCount']?.toInt();
    printType = json['printType']?.toString();
    if (json['categories'] != null) {
      final v = json['categories'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      categories = arr0;
    }
    maturityRating = json['maturityRating']?.toString();
    allowAnonLogging = json['allowAnonLogging'];
    contentVersion = json['contentVersion']?.toString();
    panelizationSummary = (json['panelizationSummary'] != null)
        ? SomeRootEntityItemsVolumeInfoPanelizationSummary.fromJson(
            json['panelizationSummary'])
        : null;
    imageLinks = (json['imageLinks'] != null)
        ? SomeRootEntityItemsVolumeInfoImageLinks.fromJson(json['imageLinks'])
        : null;
    language = json['language']?.toString();
    previewLink = json['previewLink']?.toString();
    infoLink = json['infoLink']?.toString();
    canonicalVolumeLink = json['canonicalVolumeLink']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['subtitle'] = subtitle;
    if (authors != null) {
      final v = authors;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['authors'] = arr0;
    }
    data['publisher'] = publisher;
    data['publishedDate'] = publishedDate;
    data['description'] = description;
    if (industryIdentifiers != null) {
      final v = industryIdentifiers;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['industryIdentifiers'] = arr0;
    }
    if (readingModes != null) {
      data['readingModes'] = readingModes!.toJson();
    }
    data['pageCount'] = pageCount;
    data['printType'] = printType;
    if (categories != null) {
      final v = categories;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['categories'] = arr0;
    }
    data['maturityRating'] = maturityRating;
    data['allowAnonLogging'] = allowAnonLogging;
    data['contentVersion'] = contentVersion;
    if (panelizationSummary != null) {
      data['panelizationSummary'] = panelizationSummary!.toJson();
    }
    if (imageLinks != null) {
      data['imageLinks'] = imageLinks!.toJson();
    }
    data['language'] = language;
    data['previewLink'] = previewLink;
    data['infoLink'] = infoLink;
    data['canonicalVolumeLink'] = canonicalVolumeLink;
    return data;
  }
}

class SomeRootEntityItems {
/*
{
  "kind": "books#volume",
  "id": "RMCtDwAAQBAJ",
  "etag": "jHau3qR7PeU",
  "selfLink": "https://www.googleapis.com/books/v1/volumes/RMCtDwAAQBAJ",
  "volumeInfo": {
    "title": "The Illustrated World of Tolkien",
    "subtitle": "An Exquisite Reference Guide to Tolkien's World and the Artists his Vision Inspired",
    "authors": [
      "David Day"
    ],
    "publisher": "Hachette UK",
    "publishedDate": "2019-10-19",
    "description": "Tolkien's works have inspired artists for generations and have given rise to myriad interpretations of the rich and magical worlds he created. The Illustrated World of Tolkien gathers together artworks and essays from expert illustrators, painters and etchers, and fascinating and scholarly writing from renowned Tolkien expert David Day, and is an exquisite reference guide for any fan of Tolkien's work, Tolkien's world and the imaginative brilliance his vision inspired. This work is unofficial and is not authorized by the Tolkien Estate or HarperCollins Publishers.",
    "industryIdentifiers": [
      {
        "type": "ISBN_13",
        "identifier": "9780753734049"
      }
    ],
    "readingModes": {
      "text": true,
      "image": false
    },
    "pageCount": 288,
    "printType": "BOOK",
    "categories": [
      "Art"
    ],
    "maturityRating": "NOT_MATURE",
    "allowAnonLogging": true,
    "contentVersion": "1.2.2.0.preview.2",
    "panelizationSummary": {
      "containsEpubBubbles": false,
      "containsImageBubbles": false
    },
    "imageLinks": {
      "smallThumbnail": "http://books.google.com/books/content?id=RMCtDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
      "thumbnail": "http://books.google.com/books/content?id=RMCtDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
    },
    "language": "en",
    "previewLink": "http://books.google.com.tr/books?id=RMCtDwAAQBAJ&printsec=frontcover&dq=Tolkien&hl=&cd=21&source=gbs_api",
    "infoLink": "https://play.google.com/store/books/details?id=RMCtDwAAQBAJ&source=gbs_api",
    "canonicalVolumeLink": "https://play.google.com/store/books/details?id=RMCtDwAAQBAJ"
  },
  "saleInfo": {
    "country": "TR",
    "saleability": "FOR_SALE",
    "isEbook": true,
    "listPrice": {
      "amount": 1360.55,
      "currencyCode": "TRY"
    },
    "retailPrice": {
      "amount": 1360.55,
      "currencyCode": "TRY"
    },
    "buyLink": "https://play.google.com/store/books/details?id=RMCtDwAAQBAJ&rdid=book-RMCtDwAAQBAJ&rdot=1&source=gbs_api",
    "offers": [
      {
        "finskyOfferType": 1,
        "listPrice": {
          "amountInMicros": 1360550000,
          "currencyCode": "TRY"
        },
        "retailPrice": {
          "amountInMicros": 1360550000,
          "currencyCode": "TRY"
        }
      }
    ]
  },
  "accessInfo": {
    "country": "TR",
    "viewability": "PARTIAL",
    "embeddable": true,
    "publicDomain": false,
    "textToSpeechPermission": "ALLOWED",
    "epub": {
      "isAvailable": true,
      "acsTokenLink": "http://books.google.com.tr/books/download/The_Illustrated_World_of_Tolkien-sample-epub.acsm?id=RMCtDwAAQBAJ&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api"
    },
    "pdf": {
      "isAvailable": false
    },
    "webReaderLink": "http://play.google.com/books/reader?id=RMCtDwAAQBAJ&hl=&source=gbs_api",
    "accessViewStatus": "SAMPLE",
    "quoteSharingAllowed": false
  },
  "searchInfo": {
    "textSnippet": "This work is unofficial and is not authorized by the Tolkien Estate or HarperCollins Publishers."
  }
} 
*/

  String? kind;
  String? id;
  String? etag;
  String? selfLink;
  SomeRootEntityItemsVolumeInfo? volumeInfo;
  SomeRootEntityItemsSaleInfo? saleInfo;
  SomeRootEntityItemsAccessInfo? accessInfo;
  SomeRootEntityItemsSearchInfo? searchInfo;

  SomeRootEntityItems({
    this.kind,
    this.id,
    this.etag,
    this.selfLink,
    this.volumeInfo,
    this.saleInfo,
    this.accessInfo,
    this.searchInfo,
  });
  SomeRootEntityItems.fromJson(Map<String, dynamic> json) {
    kind = json['kind']?.toString();
    id = json['id']?.toString();
    etag = json['etag']?.toString();
    selfLink = json['selfLink']?.toString();
    volumeInfo = (json['volumeInfo'] != null)
        ? SomeRootEntityItemsVolumeInfo.fromJson(json['volumeInfo'])
        : null;
    saleInfo = (json['saleInfo'] != null)
        ? SomeRootEntityItemsSaleInfo.fromJson(json['saleInfo'])
        : null;
    accessInfo = (json['accessInfo'] != null)
        ? SomeRootEntityItemsAccessInfo.fromJson(json['accessInfo'])
        : null;
    searchInfo = (json['searchInfo'] != null)
        ? SomeRootEntityItemsSearchInfo.fromJson(json['searchInfo'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['kind'] = kind;
    data['id'] = id;
    data['etag'] = etag;
    data['selfLink'] = selfLink;
    if (volumeInfo != null) {
      data['volumeInfo'] = volumeInfo!.toJson();
    }
    if (saleInfo != null) {
      data['saleInfo'] = saleInfo!.toJson();
    }
    if (accessInfo != null) {
      data['accessInfo'] = accessInfo!.toJson();
    }
    if (searchInfo != null) {
      data['searchInfo'] = searchInfo!.toJson();
    }
    return data;
  }
}

class SomeRootEntity {
/*
{
  "kind": "books#volumes",
  "totalItems": 1222,
  "items": [
    {
      "kind": "books#volume",
      "id": "RMCtDwAAQBAJ",
      "etag": "jHau3qR7PeU",
      "selfLink": "https://www.googleapis.com/books/v1/volumes/RMCtDwAAQBAJ",
      "volumeInfo": {
        "title": "The Illustrated World of Tolkien",
        "subtitle": "An Exquisite Reference Guide to Tolkien's World and the Artists his Vision Inspired",
        "authors": [
          "David Day"
        ],
        "publisher": "Hachette UK",
        "publishedDate": "2019-10-19",
        "description": "Tolkien's works have inspired artists for generations and have given rise to myriad interpretations of the rich and magical worlds he created. The Illustrated World of Tolkien gathers together artworks and essays from expert illustrators, painters and etchers, and fascinating and scholarly writing from renowned Tolkien expert David Day, and is an exquisite reference guide for any fan of Tolkien's work, Tolkien's world and the imaginative brilliance his vision inspired. This work is unofficial and is not authorized by the Tolkien Estate or HarperCollins Publishers.",
        "industryIdentifiers": [
          {
            "type": "ISBN_13",
            "identifier": "9780753734049"
          }
        ],
        "readingModes": {
          "text": true,
          "image": false
        },
        "pageCount": 288,
        "printType": "BOOK",
        "categories": [
          "Art"
        ],
        "maturityRating": "NOT_MATURE",
        "allowAnonLogging": true,
        "contentVersion": "1.2.2.0.preview.2",
        "panelizationSummary": {
          "containsEpubBubbles": false,
          "containsImageBubbles": false
        },
        "imageLinks": {
          "smallThumbnail": "http://books.google.com/books/content?id=RMCtDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
          "thumbnail": "http://books.google.com/books/content?id=RMCtDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
        },
        "language": "en",
        "previewLink": "http://books.google.com.tr/books?id=RMCtDwAAQBAJ&printsec=frontcover&dq=Tolkien&hl=&cd=21&source=gbs_api",
        "infoLink": "https://play.google.com/store/books/details?id=RMCtDwAAQBAJ&source=gbs_api",
        "canonicalVolumeLink": "https://play.google.com/store/books/details?id=RMCtDwAAQBAJ"
      },
      "saleInfo": {
        "country": "TR",
        "saleability": "FOR_SALE",
        "isEbook": true,
        "listPrice": {
          "amount": 1360.55,
          "currencyCode": "TRY"
        },
        "retailPrice": {
          "amount": 1360.55,
          "currencyCode": "TRY"
        },
        "buyLink": "https://play.google.com/store/books/details?id=RMCtDwAAQBAJ&rdid=book-RMCtDwAAQBAJ&rdot=1&source=gbs_api",
        "offers": [
          {
            "finskyOfferType": 1,
            "listPrice": {
              "amountInMicros": 1360550000,
              "currencyCode": "TRY"
            },
            "retailPrice": {
              "amountInMicros": 1360550000,
              "currencyCode": "TRY"
            }
          }
        ]
      },
      "accessInfo": {
        "country": "TR",
        "viewability": "PARTIAL",
        "embeddable": true,
        "publicDomain": false,
        "textToSpeechPermission": "ALLOWED",
        "epub": {
          "isAvailable": true,
          "acsTokenLink": "http://books.google.com.tr/books/download/The_Illustrated_World_of_Tolkien-sample-epub.acsm?id=RMCtDwAAQBAJ&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api"
        },
        "pdf": {
          "isAvailable": false
        },
        "webReaderLink": "http://play.google.com/books/reader?id=RMCtDwAAQBAJ&hl=&source=gbs_api",
        "accessViewStatus": "SAMPLE",
        "quoteSharingAllowed": false
      },
      "searchInfo": {
        "textSnippet": "This work is unofficial and is not authorized by the Tolkien Estate or HarperCollins Publishers."
      }
    }
  ]
} 
*/

  String? kind;
  int? totalItems;
  List<SomeRootEntityItems?>? items;

  SomeRootEntity({
    this.kind,
    this.totalItems,
    this.items,
  });
  SomeRootEntity.fromJson(Map<String, dynamic> json) {
    kind = json['kind']?.toString();
    totalItems = json['totalItems']?.toInt();
    if (json['items'] != null) {
      final v = json['items'];
      final arr0 = <SomeRootEntityItems>[];
      v.forEach((v) {
        arr0.add(SomeRootEntityItems.fromJson(v));
      });
      items = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['kind'] = kind;
    data['totalItems'] = totalItems;
    if (items != null) {
      final v = items;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['items'] = arr0;
    }
    return data;
  }
}
